# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'specvis_test2.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from slider_dial_widget import SliderDialWidget
from table_widget import CustomTableWidget

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1250, 305)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 40, 1001, 301))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        # self.graphicsView = QtWidgets.QGraphicsView(self.frame)
        # self.graphicsView.setGeometry(QtCore.QRect(10, 10, 981, 281))
        # self.graphicsView.setObjectName("graphicsView")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(1020, 10, 221, 331))
        self.groupBox_3.setObjectName("groupBox_3")
        self.frame_2 = QtWidgets.QFrame(self.groupBox_3)
        self.frame_2.setGeometry(QtCore.QRect(10, 30, 201, 71))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 81, 21))
        self.label_4.setObjectName("label_4")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_4.setGeometry(QtCore.QRect(102, 10, 91, 21))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_2.setGeometry(QtCore.QRect(30, 40, 141, 21))
        self.pushButton_2.setObjectName("pushButton_2")
        self.frame_slide = QtWidgets.QFrame(self.groupBox_3)
        self.frame_slide.setGeometry(QtCore.QRect(10, 110, 201, 81))
        self.frame_slide.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_slide.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_slide.setObjectName("frame_slide")
        # self.dial_redshift = QtWidgets.QDial(self.frame_slide)
        # self.dial_redshift.setGeometry(QtCore.QRect(10, 10, 81, 81))
        # self.dial_redshift.setObjectName("dial_redshift")
        # self.slider_redshift = QtWidgets.QSlider(self.frame_slide)
        # self.slider_redshift.setGeometry(QtCore.QRect(90, 40, 101, 22))
        # self.slider_redshift.setOrientation(QtCore.Qt.Horizontal)
        # self.slider_redshift.setObjectName("slider_redshift")
        self.slider_dial_widget = SliderDialWidget(self.frame_slide)
        self.slider_dial_widget.setGeometry(QtCore.QRect(10, 0, 181, 81))
        # self.tableWidget = QtWidgets.QTableWidget(self.groupBox_3)
        # self.tableWidget.setGeometry(QtCore.QRect(10, 200, 201, 121))
        # self.tableWidget.setObjectName("tableWidget")
        # self.tableWidget.setColumnCount(0)
        # self.tableWidget.setRowCount(0)
        self.table_redshift = CustomTableWidget(self.groupBox_3)
        self.table_redshift.setGeometry(QtCore.QRect(10, 200, 201, 121))
        self.table_redshift.setObjectName("table_redshift")

        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(90, 10, 113, 21))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 71, 21))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1250, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Spectral lines"))
        self.label_4.setText(_translate("MainWindow", "New redshift:"))
        self.pushButton_2.setText(_translate("MainWindow", "Add"))
        self.pushButton.setText(_translate("MainWindow", "Browse"))
        self.label.setText(_translate("MainWindow", "Spectrum: "))
